version: 2

# https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
python:
  install: # https://docs.readthedocs.io/en/stable/config-file/v2.html#requirements-file
    - requirements: docs/source/requirements.txt
sphinx:
  configuration: docs/source/conf.py
